### PR TITLE
Small Tutorial Added

### PR DESCRIPTION
**Pull request by Arch881010**
It adds some comments for them to notice how to create other commands. 
It also gives them a variable to apply other commands inside of it.

### CODE REVIEW

**Comment by Arch881010** [comment]
@hackermondev, any info on this? No rush but this was 2 days ago.

**Comment by hackermondev** [comment]
If you don't mind, I'm gonna wait until #12 is merged before merging this (otherwise merge conflicts)

**Comment by Arch881010** [comment]
That is fine! No worries!

**Comment by hackermondev** [comment]
@Arch881010 

Do you mind redoing everything and fixing the conflicts?
image


I didn't realize there would be conflicts in this one once I merged the other one 🤦

**Comment by Arch881010** [comment]
Issue with trying to fix the rest of the conflicts:
Mine just shortens the commands by pushing them out of the body and renaming the things inside the body as `commands` to be accessed later. They both get to the same end, only mine is condensed.

**Comment by Arch881010** [comment]
Realized I should-maybe-be able to push it down

**Comment by Arch881010** [comment]
I am not the greatest, so if you can tell me how to fix this conflict, I would love it. I have tried.

**Comment by Arch881010** [comment]
Push and Pull.

**Pull request closed without merging**
