### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by NicoGaming77**
Made the ping command actually ping the bot.

### CODE REVIEW

**Review by hackermondev — APPROVED** [review]

**Comment by Arch881010** [comment]
Message? This is an interaction. I wlll test this.

**Comment by Arch881010** [comment]
Nvm, it works.

**Comment by NicoGaming77** [comment]
> Nvm, it works.

Ok good because I didn't test it lmao.

**Comment by hackermondev** [comment]
it actually wasn't working before, i had to fix it (https://github.com/hackermondev/discord-active-developer-badge/commit/337e09340d1f9655d30cdde12fe92584192e84fd)

**Comment by NicoGaming77** [comment]
Oh of course... it's not a message it's an interaction. I should have tested it first.

**Pull request merged**
