### PR TITLE
Code imp, removing useless code

### PR DESCRIPTION
**Pull request by TrueXPixells**

### CODE REVIEW

**Comment by TrueXPixells** [comment]
@hackermondev Can u look this PR?

**Comment by hackermondev** [comment]
i'll look at it later this afternoon

**Comment by Arch881010** [comment]
Only statement is that (the one that changes app.js)`const client = new Client({ intents: [GatewayIntentBits.Guilds] });` 
is rewritten to 
`const client = new Client({ intents: [] });`
Not changing the last one does indeed make a difference and throws an error.

**Comment by TrueXPixells** [comment]
> Only statement is that (the one that changes app.js)`const client = new Client({ intents: [GatewayIntentBits.Guilds] });` is rewritten to `const client = new Client({ intents: [] });` Not changing the last one does indeed make a difference and throws an error.

this bot isnt using guilds, only global slash commands, so i dont need anything bits

**Comment by Arch881010** [comment]
True, but I'm just stating, the pull request doesn't show those changes. `const { Client, REST, Routes, GatewayIntentBits } = require('discord.js');` -> `const { Client, Routes } = require('discord.js');` is shown; where as my statement doesn't show any changes.

**Review by hackermondev — CHANGES_REQUESTED** [review]
[``package-lock.json`` shouldn't be in ``.gitignore`` or deleted.](https://www.linkedin.com/pulse/packagejson-vs-package-lockjson-dehvon-curtis/)

**Comment by TrueXPixells** [comment]
We in midnight 🥱

**Comment by Arch881010** [comment]
I'm waiting on you for mine to work. No rush though!

**Pull request merged**
