### PR TITLE
Update README.md - Minor Fixes & Changes

### PR DESCRIPTION
**Pull request by 1RB**
Fixed some stuff:

* fixed broken hyperlink
* added discord badge

### CODE REVIEW

**Comment by Arch881010** [comment]
I see nothing wrong with this PR.

**Review by CidQu — APPROVED** [review]
LGTM

**Comment by hackermondev** [comment]
Will review this in a few hours.

**Review by Arch881010 — CHANGES_REQUESTED** [review]
discordinvite-img
Failed to load the image in replit.

**Comment by Arch881010** [comment]
@hackermondev, poke. Said you would check in a few hours.

**Review by hackermondev — APPROVED** [review]

**Pull request merged**
